routes/web.php
<?php

use App\Http\Controllers\IdeaController;
use Illuminate\Support\Facades\Route;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

//HomePage
Route::get('/', [IdeaController::class, 'index'])->name('idea.index');
Route::get('/ideas/{idea:slug}', [IdeaController::class, 'show'])->name('idea.show');

require __DIR__ . '/auth.php';

app/Http/Livewire/AddComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use App\Models\Comment;
use Livewire\Component;
use Illuminate\Http\Response;
use App\Notifications\CommentAdded;
use App\Http\Livewire\Traits\WithAuthRedirects;

class AddComment extends Component
{
	use WithAuthRedirects;

	public $idea;

	public $comment;

	protected $rules = [
		'comment' => ['required', 'min:4'],
	];

	public function mount(Idea $idea)
	{
		$this->idea = $idea;
	}

	public function addComment()
	{
		if (auth()->guest())
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$this->validate();

		$newComment = Comment::create([
			'user_id'   => auth()->id(),
			'idea_id'   => $this->idea->id,
			'status_id' => 1,
			'body'      => $this->comment,
		]);

		$this->reset('comment');

		$this->idea->user->notify(new CommentAdded($newComment));

		$this->emit('commentWasAdded', 'Comment was posted!');
	}

	public function render()
	{
		return view('livewire.add-comment');
	}
}

app/Http/Livewire/CommentNotifications.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use App\Models\Comment;
use Livewire\Component;
use Illuminate\Http\Response;
use Illuminate\Notifications\DatabaseNotification;

class CommentNotifications extends Component
{
	const NOTIFICATION_THRESHOLD = 20;

	public $notifications;

	public $notificationCount;

	public $isLoading;

	protected $listeners = ['getNotifications'];

	public function mount()
	{
		$this->notifications = collect([]);
		$this->isLoading = true;
		$this->getNotificationCount();
	}

	public function getNotificationCount()
	{
		$this->notificationCount = auth()->user()->unreadNotifications()->count();

		if ($this->notificationCount > self::NOTIFICATION_THRESHOLD)
		{
			$this->notificationCount = self::NOTIFICATION_THRESHOLD . '+';
		}
	}

	public function getNotifications()
	{
		$this->notifications = auth()->user()
			->unreadNotifications()
			->latest()
			->take(self::NOTIFICATION_THRESHOLD)
			->get();

		$this->isLoading = false;
	}

	public function markAllAsRead()
	{
		if (auth()->guest())
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		auth()->user()->unreadNotifications->markAsRead();
		$this->getNotificationCount();
		$this->getNotifications();
	}

	public function scrollToComment($notification)
	{
		$idea = Idea::find($notification->data['idea_id']);
		if (!$idea)
		{
			session()->flash('error_message', 'This idea no longer exists!');

			return redirect()->route('idea.index');
		}

		$comment = Comment::find($notification->data['comment_id']);
		if (!$comment)
		{
			session()->flash('error_message', 'This comment no longer exists!');

			return redirect()->route('idea.index');
		}

		$comments = $idea->comments()->pluck('id');
		$indexOfComment = $comments->search($comment->id);

		$page = (int) ($indexOfComment / $comment->getPerPage()) + 1;

		session()->flash('scrollToComment', $comment->id);

		return redirect()->route('idea.show', [
			'idea' => $notification->data['idea_slug'],
			'page' => $page,
		]);
	}

	public function markAsRead($notificationId)
	{
		if (auth()->guest())
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$notification = DatabaseNotification::findOrFail($notificationId);
		$notification->markAsRead();

		$this->scrollToComment($notification);
	}

	public function render()
	{
		return view('livewire.comment-notifications');
	}
}

app/Http/Livewire/CreateIdea.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use Livewire\Component;
use App\Models\Category;
use Illuminate\Http\Response;
use App\Http\Livewire\Traits\WithAuthRedirects;

class CreateIdea extends Component
{
	use WithAuthRedirects;

	public $title;

	public $category = 1;

	public $description;

	// TODO: MOVE RULES TO ITS OWN REQUEST
	protected $rules = [
		'title'       => ['required', 'min:4'],
		'category'    => ['required', 'integer', 'exists:categories,id'],
		'description' => ['required', 'min:4'],
	];

	public function render()
	{
		return view('livewire.create-idea', [
			'categories' => Category::all(),
		]);
	}

	public function createIdea()
	{
		if (auth()->check())
		{
			$this->validate();

			Idea::create([
				'user_id'     => auth()->id(),
				'category_id' => $this->category,
				'status_id'   => 1,
				'title'       => $this->title,
				'description' => $this->description,
			]);
			session()->flash('success_message', 'Idea was added successfully!');

			$this->reset();

			return redirect()->route('idea.index');
		}
		abort(Response::HTTP_FORBIDDEN);
	}
}

app/Http/Livewire/DeleteComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class DeleteComment extends Component
{
	public ?Comment $comment;

	protected $listeners = ['setDeleteComment'];

	public function setDeleteComment($commentId)
	{
		$this->comment = Comment::findOrFail($commentId);
		$this->emit('deleteCommentWasSet');
	}

	public function deleteComment()
	{
		if (auth()->guest() || auth()->user()->cannot('delete', $this->comment))
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		Comment::destroy($this->comment->id);
		$this->comment = null;
		$this->emit('commentWasDeleted', 'Comment was deleted!');
	}

	public function render()
	{
		return view('livewire.delete-comment');
	}
}

app/Http/Livewire/DeleteIdea.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use Livewire\Component;
use Illuminate\Http\Response;

class DeleteIdea extends Component
{
	public $idea;

	public function mount(Idea $idea)
	{
		$this->idea = $idea;
	}

	public function deleteIdea()
	{
		if (auth()->guest() || auth()->user()->cannot('delete', $this->idea))
		{
			abort(Response::HTTP_FORBIDDEN);
		}
		Idea::destroy($this->idea->id);

		session()->flash('success_message', 'Idea was deleted successfully!');
		
		return redirect()->route('idea.index');
	}

	public function render()
	{
		return view('livewire.delete-idea');
	}
}

app/Http/Livewire/EditComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Livewire\Component;
use Illuminate\Http\Response;

class EditComment extends Component
{
	public Comment $comment;

	public $body;

	protected $rules = [
		'body' => ['required', 'min:4'],
	];

	protected $listeners = ['setEditComment'];

	public function setEditComment($commentId)
	{
		$this->comment = Comment::findOrFail($commentId);
		$this->body = $this->comment->body;

		$this->emit('editCommentWasSet');
	}

	public function updateComment()
	{	
        // Authorization
		if (auth()->guest() || auth()->user()->cannot('update', $this->comment))
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$this->validate();
		$this->comment->body = $this->body;
		$this->comment->save();

		$this->emit('commentWasUpdated', 'Comment was Updated!');
	}

	public function render()
	{
		return view('livewire.edit-comment');
	}
}

app/Http/Livewire/EditIdea.php
<?php

namespace App\Http\Livewire;

use Illuminate\Http\Response;
use App\Models\Category;
use App\Models\Idea;
use Livewire\Component;

class EditIdea extends Component
{
	public $idea;

	public $title;

	public $category;

	public $description;

	protected $rules = [
		'title'       => ['required', 'min:4'],
		'category'    => ['required', 'integer', 'exists:categories,id'],
		'description' => ['required', 'min:4'],
	];

	public function mount(Idea $idea)
	{
		$this->idea = $idea;
		$this->title = $idea->title;
		$this->category = $idea->category_id;
		$this->description = $idea->description;
	}

	public function updateIdea()
	{
		// Authorization
		if (auth()->guest() || auth()->user()->cannot('update', $this->idea))
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$this->validate();

		$this->idea->update([
			'title'       => $this->title,
			'category_id' => $this->category,
			'description' => $this->description,
		]);

		$this->emit('ideaWasUpdated', 'Idea was updated successfully!');
	}

	public function render()
	{
		return view('livewire.edit-idea', [
			'categories' => Category::all(),
		]);
	}
}

app/Http/Livewire/IdeaComment.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Livewire\Component;

class IdeaComment extends Component
{
	public $comment;

	public $ideaUserId;

	protected $listeners = [
		'commentWasUpdated',
		'commentWasMarkedAsSpam',
		'commentWasMarkedAsNotSpam',
	];

	public function commentWasUpdated()
	{
		$this->comment->refresh();
	}

	public function commentWasMarkedAsSpam()
	{
		$this->comment->refresh();
	}

	public function commentWasMarkedAsNotSpam()
	{
		$this->comment->refresh();
	}

	public function mount(Comment $comment, $ideaUserId)
	{
		$this->comment = $comment;
		$this->ideaUserId = $ideaUserId;
	}

	public function render()
	{
		return view('livewire.idea-comment');
	}
}

app/Http/Livewire/IdeaComments.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use App\Models\Idea;
use Livewire\Component;
use Livewire\WithPagination;

class IdeaComments extends Component
{
	use WithPagination;

	public $idea;

	protected $listeners = [
		'commentWasAdded',
		'commentWasDeleted',
		'statusWasUpdated',
	];

	public function commentWasAdded()
	{
		$this->idea->refresh();
		$this->gotoPage($this->idea->comments()->paginate()->lastPage());
	}

	public function commentWasDeleted()
	{
		$this->idea->refresh();
		$this->gotoPage(1);
	}

	public function statusWasUpdated()
	{
		$this->idea->refresh();
		$this->gotoPage($this->idea->comments()->paginate()->lastPage());
	}

	public function mount(Idea $idea)
	{
		$this->idea = $idea;
	}

	public function render()
	{
		return view('livewire.idea-comments', [
			// 'comments' => $this->idea->comments()->paginate()->withQueryString(),
			'comments' => Comment::with(['user', 'status'])->where('idea_id', $this->idea->id)->paginate()->withQueryString(),
		]);
	}
}

app/Http/Livewire/IdeaIndex.php
<?php

namespace App\Http\Livewire;

use App\Exceptions\DuplicateVoteException;
use App\Exceptions\VoteNotFoundException;
use App\Http\Livewire\Traits\WithAuthRedirects;
use App\Models\Idea;
use Livewire\Component;

class IdeaIndex extends Component
{
	use WithAuthRedirects;

	public $idea;

	public $votesCount;

	public $hasVoted;

	public function mount(Idea $idea, $votesCount)
	{
		$this->idea = $idea;
		$this->votesCount = $votesCount;
		$this->hasVoted = $idea->voted_by_user;
	}

	public function vote()
	{
		if (auth()->guest())
		{
			return $this->redirectToLogin();
		}

		if ($this->hasVoted)
		{
			try
			{
				$this->idea->removeVote(auth()->user());
			}
			catch (VoteNotFoundException $e)
			{
				// do nothing
			}
			$this->votesCount--;
			$this->hasVoted = false;
		}
		else
		{
			try
			{
				$this->idea->vote(auth()->user());
			}
			catch (DuplicateVoteException $e)
			{
				// do nothing
			}
			$this->votesCount++;
			$this->hasVoted = true;
		}
	}

	public function render()
	{
		return view('livewire.idea-index');
	}
}

app/Http/Livewire/IdeaShow.php
<?php

namespace App\Http\Livewire;

use App\Exceptions\DuplicateVoteException;
use App\Exceptions\VoteNotFoundException;
use App\Http\Livewire\Traits\WithAuthRedirects;
use App\Models\Idea;
use Livewire\Component;

class IdeaShow extends Component
{
	use WithAuthRedirects;

	public $idea;

	public $votesCount;

	public $hasVoted;

	protected $listeners = [
		'statusWasUpdated',
		'statusWasUpdatedError',
		'ideaWasUpdated',
		'ideaWasMarkedAsSpam',
		'ideaWasMarkedAsNotSpam',
		'commentWasAdded',
		'commentWasDeleted',
	];

	public function mount(Idea $idea, $votesCount)
	{
		$this->idea = $idea;
		$this->votesCount = $votesCount;
		$this->hasVoted = $idea->isVotedByUser(auth()->user());
	}

	public function statusWasUpdatedError()
	{
		$this->idea->refresh();
	}

	public function statusWasUpdated()
	{
		$this->idea->refresh();
	}

	public function ideaWasUpdated()
	{
		$this->idea->refresh();
	}

	public function ideaWasMarkedAsSpam()
	{
		$this->idea->refresh();
	}

	public function ideaWasMarkedAsNotSpam()
	{
		$this->idea->refresh();
	}

	public function commentWasAdded()
	{
		$this->idea->refresh();
	}

	public function commentWasDeleted()
	{
		$this->idea->refresh();
	}

	public function vote()
	{
		if (auth()->guest())
		{
			return $this->redirectToLogin();
		}

		if ($this->hasVoted)
		{
			try
			{
				$this->idea->removeVote(auth()->user());
			}
			catch (VoteNotFoundException $e)
			{
				// do nothing
			}
			$this->votesCount--;
			$this->hasVoted = false;
		}
		else
		{
			try
			{
				$this->idea->vote(auth()->user());
			}
			catch (DuplicateVoteException $e)
			{
				// do nothing
			}
			$this->votesCount++;
			$this->hasVoted = true;
		}
	}

	public function render()
	{
		return view('livewire.idea-show');
	}
}

app/Http/Livewire/IdeasIndex.php
<?php

namespace App\Http\Livewire;

use App\Models\Idea;
use App\Models\Vote;
use App\Models\Status;
use Livewire\Component;
use App\Models\Category;
use Livewire\WithPagination;
use App\Http\Livewire\Traits\WithAuthRedirects;

class IdeasIndex extends Component
{
	use WithPagination, WithAuthRedirects;

	public $status;

	public $category;

	public $filter;

	public $search;

	protected $queryString = [
		'status',
		'category',
		'filter',
		'search',
	];

	protected $listeners = ['queryStringUpdatedStatus'];

	public function mount()
	{
		$this->status = request()->status ?? 'All';
	}

	public function queryStringUpdatedStatus($newStatus)
	{
		$this->resetPage();
		$this->status = $newStatus;
	}

	public function updatingCategory()
	{
		$this->resetPage();
	}

	public function updatingFilter()
	{
		$this->resetPage();
	}

	public function updatingSearch()
	{
		$this->resetPage();
	}

	public function updatedFilter()
	{
		if ($this->filter === 'My Ideas')
		{
			if (auth()->guest())
			{
				return $this->redirectToLogin();
			}
		}
	}

	public function render()
	{
		$statuses = Status::all()->pluck('id', 'name');
		$categories = Category::all();
		return view('livewire.ideas-index', [
			'ideas' => Idea::with('user', 'category', 'status')
				->when($this->status && $this->status !== 'All', function ($query) use ($statuses) {
					return $query->where('status_id', $statuses->get($this->status));
				})->when($this->category && $this->category !== 'All Categories', function ($query) use ($categories) {
					return $query->where('category_id', $categories->pluck('id', 'name')->get($this->category));
				})->when($this->filter && $this->filter === 'Top Voted', function ($query) {
					return $query->orderByDesc('votes_count');
				})->when($this->filter && $this->filter === 'My Ideas', function ($query) {
					return $query->where('user_id', auth()->id());
				})->when($this->filter && $this->filter === 'Spam Ideas', function ($query) {
					return $query->where('spam_reports', '>', 0)->orderByDesc('spam_reports');
				})->when($this->filter && $this->filter === 'Spam Comments', function ($query) {
					return $query->whereHas('comments', function ($query) {
						$query->where('spam_reports', '>', 0);
					});
				})->when(strlen($this->search) >= 3, function ($query) {
					return $query->where('title', 'like', '%' . $this->search . '%');
				})
				->addSelect(['voted_by_user' => Vote::select('id')
					->where('user_id', auth()->id())
					->whereColumn('idea_id', 'ideas.id'),
				])
				->withCount('votes')
				->withCount('comments')
				->orderBy('id', 'desc')
				->simplePaginate()
				->withQueryString(),
			'categories' => $categories,
		]);
	}
}

app/Http/Livewire/MarkCommentAsNotSpam.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class MarkCommentAsNotSpam extends Component
{
	public Comment $comment;

	protected $listeners = ['setMarkAsNotSpamComment'];

	public function setMarkAsNotSpamComment($commentId)
	{
		$this->comment = Comment::findOrFail($commentId);

		$this->emit('markAsNotSpamCommentWasSet');
	}

	public function markAsNotSpam()
	{
		if (auth()->guest() || !auth()->user()->isAdmin())
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$this->comment->spam_reports = 0;
		$this->comment->save();

		$this->emit('commentWasMarkedAsNotSpam', 'Comment spam counter was reset!');
	}

	public function render()
	{
		return view('livewire.mark-comment-as-not-spam');
	}
}

app/Http/Livewire/MarkCommentAsSpam.php
<?php

namespace App\Http\Livewire;

use App\Models\Comment;
use Illuminate\Http\Response;
use Livewire\Component;

class MarkCommentAsSpam extends Component
{
	public Comment $comment;

	protected $listeners = ['setMarkAsSpamComment'];

	public function setMarkAsSpamComment($commentId)
	{
		$this->comment = Comment::findOrFail($commentId);

		$this->emit('markAsSpamCommentWasSet');
	}

	public function markAsSpam()
	{
		if (auth()->guest())
		{
			abort(Response::HTTP_FORBIDDEN);
		}

		$this->comment->spam_reports++;
		$this->comment->save();

		$this->emit('commentWasMarkedAsSpam', 'Comment was marked as spam!');
	}

	public function render()
	{
		return view('livewire.mark-comment-as-spam');
	}
}

resources/views/livewire/comment-notifications.blade.php
<div    
    wire:poll="getNotificationCount"
    x-data="{ isOpen: false }"
    class="relative"
    >
    <button @click="isOpen = !isOpen
        if (isOpen) {
            Livewire.emit('getNotifications')
        }
    ">
        <svg class="w-8 h-8 text-gray-400" viewBox="0 0 20 20" fill="currentColor">
            <path
                d="M10 2a6 6 0 00-6 6v3.586l-.707.707A1 1 0 004 14h12a1 1 0 00.707-1.707L16 11.586V8a6 6 0 00-6-6zM10 18a3 3 0 01-3-3h6a3 3 0 01-3 3z" />
        </svg>
        @if ($notificationCount)
            <div
                class="absolute flex items-center justify-center w-6 h-6 text-white border-2 rounded-full bg-red text-xxs -top-1 -right-1">
                {{ $notificationCount }}</div>
        @endif

    </button>
    <ul class="absolute z-10 overflow-y-auto text-sm text-left text-gray-700 bg-white w-76 md:w-76 shadow-dialog rounded-xl max-h-128 -right-28 md:-right-12"
        {{-- style="right: -46px" --}} x-cloak x-show.transition.origin.top="isOpen" @click.away="isOpen = false"
        @keydown.escape.window="isOpen = false">
        @if ($notifications->isNotEmpty() && !$isLoading)
            @foreach ($notifications as $notification)
                <li>
                    <a href="{{ route('idea.show', $notification->data['idea_slug']) }}"
                         @click.prevent="
                            isOpen = false" 
                        wire:click.prevent="markAsRead('{{ $notification->id }}')"
                        class="flex px-5 py-3 transition duration-150 ease-in hover:bg-gray-100">
                        <img src="{{ $notification->data['user_avatar'] }}" class="w-10 h-10 rounded-xl" alt="avatar">
                        <div class="ml-4">
                            <div class="line-clamp-6">
                                <span class="font-semibold">{{ $notification->data['user_name'] }}</span> commented on
                                <span class="font-semibold">{{ $notification->data['idea_title'] }}</span>:
                                <span>"{{ $notification->data['comment_body'] }}"</span>
                            </div>
                            <div class="mt-2 text-xs text-gray-500">{{ $notification->created_at->diffForHumans() }}
                            </div>
                        </div>
                    </a>
                </li>
            @endforeach

            <li class="text-center border-t border-gray-300">
                <button wire:click="markAllAsRead" @click="isOpen = false"
                    class="block w-full px-5 py-4 font-semibold transition duration-150 ease-in hover:bg-gray-100">
                    Mark all as read
                </button>
            </li>
        @elseif ($isLoading)
            @foreach (range(1, 3) as $item)
                <li class="flex items-center px-5 py-3 transition duration-150 ease-in animate-pulse">
                    <div class="w-10 h-10 bg-gray-200 rounded-xl"></div>
                    <div class="flex-1 ml-4 space-y-2">
                        <div class="w-full h-4 bg-gray-200 rounded"></div>
                        <div class="w-full h-4 bg-gray-200 rounded"></div>
                        <div class="w-1/2 h-4 bg-gray-200 rounded"></div>
                    </div>
                </li>
            @endforeach
        @else
            <li class="w-40 py-6 mx-auto">
                <img src="{{ asset('img/no-ideas.svg') }}" alt="No Ideas" class="mx-auto mix-blend-luminosity">
                <div class="mt-6 font-bold text-center text-gray-400">No new notifications</div>
            </li>
        @endif
    </ul>
</div>

resources/views/livewire/delete-comment.blade.php
<x-modal-confirm
    livewire-event-to-open-modal="deleteCommentWasSet"
    event-to-close-modal="commentWasDeleted"
    modal-title="Delete Comment"
    modal-description="Are you sure you want to delete this comment? This action cannot be undone."
    modal-confirm-button-text="Delete"
    wire-click="deleteComment"
/>

resources/views/livewire/idea-comments.blade.php
<div>
    @if ($comments->isNotEmpty())
        <div class="relative pt-4 my-8 mt-1 space-y-6 comments-container md:ml-22">

            @foreach ($comments as $comment)
                <livewire:idea-comment :key="$comment->id" :comment="$comment" :ideaUserId="$idea->user->id" />
            @endforeach
        </div>
        <div class="my-8 md:ml-22">
            {{ $comments->onEachSide(1)->links() }}
        </div>
    @else
        <div class="mx-auto mt-12 w-70">
            <img src="{{ asset('img/no-ideas.svg') }}" alt="No Ideas" class="mx-auto mix-blend-luminosity">
            <div class="mt-6 font-bold text-center text-gray-400">No comments yet...</div>
        </div>
    @endif
</div>

resources/views/livewire/idea-index.blade.php
<div x-data @click="
!['button','svg','path','a'].includes($event.target.tagName.toLowerCase()) && $event.target.closest('.idea-container').querySelector('.idea-link').click()
" class="flex transition duration-150 ease-in bg-white cursor-pointer idea-container hover:shadow-card rounded-xl">
    <div class="hidden px-5 py-8 border-r border-gray-100 md:block">
        <div class="text-center">
            <div class="text-2xl font-semibold @if ($hasVoted) text-blue @endif">{{ $votesCount }}</div>
            <div class="text-gray-500">Votes</div>
        </div>
        <div class="mt-8">
            @if ($hasVoted)
                <button wire:click.prevent="vote"
                    class="w-20 px-4 py-3 font-bold text-white uppercase transition duration-150 ease-in border bg-blue border-blue hover:bg-blue-hover text-xxs rounded-xl">Voted</button>
            @else
                <button wire:click.prevent="vote"
                    class="w-20 px-4 py-3 font-bold uppercase transition duration-150 ease-in bg-gray-200 border border-gray-200 hover:border-gray-400 text-xxs rounded-xl">Vote</button>
            @endif
        </div>
    </div>
    <div class="flex flex-col flex-1 px-2 py-6 md:flex-row">
        <div class="flex-none mx-2 md:mx-0 ">
            <a href="{{ route('idea.show', [$idea]) }}">
                <img src="{{ $idea->user->getAvatar() }}" alt="user avatar" width="60" height="60" alt="avatar"
                    class="w-14 h-14 rounded-xl">
            </a>
        </div>
        <div class="flex flex-col justify-between w-full mx-2 md:mx-4">
            <h4 class="mt-2 text-xl font-semibold md:mt-0">
                <a href="{{ route('idea.show', [$idea]) }}" class="hover:underline idea-link">{{ $idea->title }}</a>
            </h4>
            <div class="mt-3 text-gray-600 line-clamp-3">
                @admin
                @if ($idea->spam_reports > 0)
                    <div class="mb-2 text-red">Spam Reports: {{ $idea->spam_reports }}</div>
                @endif
                @endadmin
                {{ $idea->description }}

            </div>
            <div class="flex flex-col justify-between mt-6 md:items-center md:flex-row">
                <div class="flex items-center space-x-2 text-xs font-semibold text-gray-400">
                    <div>{{ $idea->created_at->diffForHumans() }}</div>
                    <div>&bull;</div>
                    <div>{{ $idea->category->name }}</div>
                    <div>&bull;</div>
                    <div wire:ignore class="text-gray-900">{{ $idea->comments_count }} comments</div>
                </div>
                <div x-data="{ isOpen: false }" class="flex items-center mt-4 space-x-2 md:mt-0">
                    <div class="{{ 'status-'.Str::kebab($idea->status->name) }} text-xxs font-bold uppercase leading-none rounded-full text-center w-28 h-7 py-2 px-4">{{ $idea->status->name }}</div>
                    <button @click="isOpen = !isOpen"
                        class="relative px-3 py-2 transition duration-150 ease-in bg-gray-100 rounded-full hover:bg-gray-200 h-7">
                        {{-- TODO: MOVE SVG TO ITS BLADE COMPONENT --}}
                        <svg fill="currentColor" width="24" height="6">
                            <path
                                d="M2.97.061A2.969 2.969 0 000 3.031 2.968 2.968 0 002.97 6a2.97 2.97 0 100-5.94zm9.184 0a2.97 2.97 0 100 5.939 2.97 2.97 0 100-5.939zm8.877 0a2.97 2.97 0 10-.003 5.94A2.97 2.97 0 0021.03.06z"
                                style="color: rgba(163, 163, 163, .5)">
                        </svg>
                        <ul x-show.transition.origin.top.left="isOpen" @click.away="isOpen = false" x-cloak
                            @keydown.escape.window="isOpen = false"
                            class="absolute right-0 z-10 py-3 font-semibold text-left bg-white w-44 shadow-dialog rounded-xl md:ml-8 top-8 md:top-6 md:left-0">
                            <li><a href="#"
                                    class="block px-5 py-3 transition duration-150 ease-in hover:bg-gray-100">Mark
                                    as Spam</a></li>
                            <li><a href="#"
                                    class="block px-5 py-3 transition duration-150 ease-in hover:bg-gray-100">Delete
                                    Post</a></li>
                        </ul>
                    </button>
                </div>
                <div class="flex items-center mt-4 md:hidden md:mt-0">
                    <div class="h-10 px-4 py-2 pr-8 text-center bg-gray-100 rounded-xl">
                        <div class="text-xl leading-snug @if ($hasVoted) text-blue @endif">{{ $votesCount }}</div>
                        <div class="font-semibold leading-none text-gray-400 text-xxs">Votes</div>
                    </div>
                    @if ($hasVoted)
                        <button wire:click.prevent="vote"
                            class="w-20 px-4 py-3 font-bold text-white uppercase transition duration-150 ease-in border bg-blue border-blue hover:bg-blue-hover text-xxs rounded-xl">Voted</button>
                    @else
                        <button wire:click.prevent="vote" f
                            class="w-20 px-4 py-3 font-bold uppercase transition duration-150 ease-in bg-gray-200 border border-gray-200 hover:border-gray-400 text-xxs rounded-xl">Vote</button>
                    @endif
                </div>
            </div>
        </div>
    </div>
</div>